#!/bin/sh

if [ $(uname) = "Linux" -o $(uname) = "Darwin" ]; then
    pathCmd="readlink -f"
else
    pathCmd="realpath"
fi

BASEDIR=`dirname $($pathCmd $0)`

export CLASSPATH=$CLASSPATH:$BASEDIR/dist/princess-all.jar

exec java -Xss20000k -Xmx1500m ap.DialogMain "$@"
