#!/bin/sh

if [ $(uname) = "Linux" -o $(uname) = "Darwin" ]; then
    pathCmd="readlink -f"
else
    pathCmd="realpath"
fi

JAVACUP=/usr/share/java/java-cup-0.11b.jar

BASEDIR=`dirname $($pathCmd $0)`
ASSEMBLY=$BASEDIR/target/scala-2.*/Princess-assembly*
NATIVE=$BASEDIR/target/native-image/Princess

export JAVA_OPTS="-Xss20000k -Xmx1500m"

if [ -f $NATIVE ]; then
    exec $NATIVE "$@"
elif [ -f $ASSEMBLY ]; then
    exec java $JAVA_OPTS -jar $ASSEMBLY "$@"
else
    export CLASSPATH=$CLASSPATH:$BASEDIR/bin:$BASEDIR/smt-parser/smt-parser.jar:$BASEDIR/parser/parser.jar:$JAVACUP
    exec scala ap.CmdlMain "$@"    
fi


