#!/bin/sh

if [ $(uname) = "Linux" -o $(uname) = "Darwin" ]; then
    pathCmd="readlink -f"
else
    pathCmd="realpath"
fi

BASEDIR=`dirname $($pathCmd $0)`
EXTLIBSDIR=$BASEDIR/extlibs
ASSEMBLY=$BASEDIR/target/scala-2.*/Princess-assembly*

export JAVA_OPTS="-Xss20000k -Xmx1500m"

if [ -f $ASSEMBLY ]; then
    exec java $JAVA_OPTS -jar $ASSEMBLY "$@"
else
    export CLASSPATH=$CLASSPATH:$BASEDIR/bin:$BASEDIR/smt-parser/smt-parser.jar:$BASEDIR/parser/parser.jar:$EXTLIBSDIR/java-cup-11a.jar    
    exec scala ap.CmdlMain "$@"    
fi


