#!/bin/sh

if [ $(uname) = "Linux" -o $(uname) = "Darwin" ]; then
    pathCmd="readlink -f"
else
    pathCmd="realpath"
fi

JAVACUP=/usr/share/java/java-cup-0.11b.jar

BASEDIR=`dirname $($pathCmd $0)`
ASSEMBLY=$BASEDIR/target/scala-2.*/Princess-assembly*

export JAVA_OPTS="-Xss20000k -Xmx1500m"

if [ -f $ASSEMBLY ]; then
    exec java $JAVA_OPTS -cp $ASSEMBLY ap.DialogMain "$@"
else
    export CLASSPATH=$CLASSPATH:$BASEDIR/bin:$BASEDIR/smt-parser/smt-parser.jar:$BASEDIR/parser/parser.jar:$JAVACUP
    exec scala ap.DialogMain "$@"
fi
