#!/bin/sh

if [ $(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ $(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi

BASEDIR=`dirname $($pathCmd $0)`
EXTLIBSDIR=$BASEDIR/extlibs

export CLASSPATH=$CLASSPATH:$BASEDIR/bin:$BASEDIR/parser/parser.jar:$EXTLIBSDIR/java-cup-11a.jar
export JAVA_OPTS="-Xss20000k"

cd $BASEDIR
exec scala ap.interpolants.WolverineInterfaceMain "$@"
