#!/bin/sh

ABSEXECUTABLE=`readlink -m $0`
BASEDIR=`dirname $0`

export CLASSPATH=$CLASSPATH:$BASEDIR/dist/princess-all.jar

cd $BASEDIR
exec java -Xss20000k -Xmx1500m -noverify ap.interpolants.WolverineInterfaceMain "$@"
