#!/bin/sh

# test the array solver

PRI=../../princess

TESTS="downwardsPropagation.smt2 \
       downwardsPropagation2.smt2 \
       arrays.smt2 arrays2.smt2 arrays3.smt2 \
       arrays4.smt2 arrays5.smt2 arrays6.smt2 \
       boolean-array.smt2 array-sorted.smt2"

$PRI "$@" $TESTS

