#!/bin/sh

PRI=../../princess

TESTS="simple0.smt2 \
       simple1.smt2 \
       simple2.smt2 \
       simple2b.smt2 \
       casts.smt2 \
       casts3.smt2 \
       realList.smt2 \
       quantifiers.smt2 \
       quantifiers2.smt2"

$PRI "$@" $TESTS

