#!/bin/sh

PRI=../../princess


TESTS="bitvectorArith3.pri bitvectorArith4.pri omegaBug.pri splitting.pri \
       bv0.pri"

$PRI "$@" $TESTS 2>&1 | grep -v "^[(!zOc]"

# For the last testcase we have to check the output precisely

$PRI "$@" closingConstraintBug.pri
