#!/bin/sh

# tests only runnable with unit resolution and clausification

PRI=../../princess

TESTS="existential.pri \
       bvsdiv.smt2 \
       bvsdiv2.smt2 \
       bvsdiv3.smt2 \
       bvsdiv5.smt2 \
       bvsdiv6.smt2 \
       bvsdiv6b.smt2 \
       bvsdiv6c.smt2 \
       bvsmod.smt2 \
       bvsmod3.smt2 \
       bvsrem.smt2 \
       bvsrem2.smt2 \
       bvshl1.smt2 \
       bvshl2.smt2 \
       bvshl3.smt2 \
       bvshl4.smt2 \
       shift2.pri \
       shift3.pri \
       shift5.pri \
       shift6.pri \
       shift7.pri \
       shift8.pri \
       bench_977.smt2 \
       bench_977b.smt2 \
       bench_977c.smt2 \
       bench_977d.smt2 \
       bench_977e.smt2 \
       rewriting_cycle.pri \
       nested_casts.pri"

$PRI "$@" $TESTS
