#!/bin/sh

unset CLASSPATH

rm -f *.class

OPTIONS="-language:implicitConversions,postfixOps,reflectiveCalls -cp `pwd`/../../bin"
RUNOPTIONS="-cp `pwd`/../../bin:."

export JAVA_OPTS="-Xss20000k -Xmx1500m"

TESTS="SetTest VectorTest PairTest"

for testname in $TESTS; do
  echo
  echo $testname
  scalac $OPTIONS $testname.scala
  scala $RUNOPTIONS $testname
done
