#!/bin/sh

# Some examples that need special settings

PRI=../../princess

$PRI "$@" -simplifyConstraints=lemmas -posUnitResolution functions2b.pri
$PRI "$@" -timeout=30000 -clausifier=none +posUnitResolution group0.pri
$PRI "$@" -timeout=30000 +posUnitResolution -constructProofs=always counterExampleBug.pri
