#!/bin/sh

# Some examples that need special settings

PRI=../../princess

$PRI "$@" -simplifyConstraints=lemmas -posUnitResolution functions2b.pri
$PRI "$@" -posUnitResolution tarskiGeometry2.pri
$PRI "$@" -timeout=30000 -clausifier=none +posUnitResolution group0.pri
$PRI "$@" -timeout=30000 +posUnitResolution -constructProofs=always counterExampleBug.pri
$PRI "$@" -timeout=30000 -constructProofs=always omega_problem__031.smt.pri
$PRI "$@" -generateTriggers=total -genTotalityAxioms +reverseFunctionalityPropagation -tightFunctionScopes ricart-agrawala7.smt2
$PRI "$@" -timeout=30000 proofBug.pri
$PRI "$@" -timeout=15000 multiplication3.pri
$PRI "$@" -generateTriggers=total -timeout=60000 vstte-problem-2-vc.pri
$PRI "$@" -timeout=30000 -generateTriggers=all +mostGeneralConstraint soldiers.pri
$PRI "$@" -timeout=30000 +triggersInConjecture -genTotalityAxioms -tightFunctionScopes -clausifier=none +boolFunsAsPreds -triggerStrategy=allMaximal +ignoreQuantifiers -generateTriggers=all GEO212+3-complete.p
$PRI "$@" -timeout=90000 -assert -constructProofs=always diamonds.10.2-no-interpolant.i.a.u.pri
$PRI "$@" -timeout=30000 +incremental -assert abbrev-interpolation.smt2

