#!/bin/sh

unset CLASSPATH

rm -f *.class

OPTIONS="-language:implicitConversions,postfixOps,reflectiveCalls -cp `pwd`/../../bin"
RUNOPTIONS="-cp `pwd`/../../bin:."

export JAVA_OPTS="-Xss20000k -Xmx1500m"

scalac $OPTIONS SimpleAPITest.scala
scala $RUNOPTIONS SimpleAPITest

scalac $OPTIONS SimpleAPITest2.scala
scala $RUNOPTIONS SimpleAPITest2

scalac $OPTIONS SimpleAPITest3.scala
scala $RUNOPTIONS SimpleAPITest3

scalac $OPTIONS SimpleAPITest4.scala
scala $RUNOPTIONS SimpleAPITest4

scalac $OPTIONS SimpleAPITest5.scala
scala $RUNOPTIONS SimpleAPITest5

scalac $OPTIONS SimpleAPITest6.scala
scala $RUNOPTIONS SimpleAPITest6

scalac $OPTIONS SimpleAPITest7.scala
scala $RUNOPTIONS SimpleAPITest7

scalac $OPTIONS SimpleAPITest8.scala
scala $RUNOPTIONS SimpleAPITest8

scalac $OPTIONS SimpleAPITest9.scala
scala $RUNOPTIONS SimpleAPITest9

scalac $OPTIONS SimpleAPITest10.scala
scala $RUNOPTIONS SimpleAPITest10

scalac $OPTIONS SimpleAPITest11.scala
scala $RUNOPTIONS SimpleAPITest11

scala $OPTIONS interpolation-bug.scala
scala $OPTIONS scope-bug.scala
scala $OPTIONS incrementality-bug.scala
scala $OPTIONS getConstraint-bug.scala

scala $OPTIONS TheoryTest.scala
scala $OPTIONS TheoryTest2.scala
scala $OPTIONS TheoryTest3.scala

scala $OPTIONS nonlinear.scala
scala $OPTIONS nonlinearInterpolation.scala
scala $OPTIONS division.scala

OPTIONS="-language:implicitConversions,postfixOps,reflectiveCalls -cp `pwd`/../../bin:`pwd`/../../extlibs/java-cup-11a.jar:`pwd`/../../smt-parser/smt-parser.jar"

scala $OPTIONS readSMTLIB.scala
scala $OPTIONS deadlock.scala
scala $OPTIONS exception.scala
scala $OPTIONS incremental.scala
scala $OPTIONS divmodprint.scala
scala $OPTIONS ADTTest.scala
scala $OPTIONS ADTTest2.scala
scala $OPTIONS pred-simplify.scala

