#!/bin/sh

unset CLASSPATH

rm -f *.class

OPTIONS="-language:implicitConversions,postfixOps,reflectiveCalls -cp `pwd`/../../bin"

scalac $OPTIONS SimpleAPITest.scala
scala -cp ../../bin:. SimpleAPITest

scalac $OPTIONS SimpleAPITest2.scala
scala -cp ../../bin:. SimpleAPITest2

scalac $OPTIONS SimpleAPITest3.scala
scala -cp ../../bin:. SimpleAPITest3

scalac $OPTIONS SimpleAPITest4.scala
scala -cp ../../bin:. SimpleAPITest4

scalac $OPTIONS SimpleAPITest5.scala
scala -cp ../../bin:. SimpleAPITest5

scalac $OPTIONS SimpleAPITest6.scala
scala -cp ../../bin:. SimpleAPITest6

scalac $OPTIONS SimpleAPITest7.scala
scala -cp ../../bin:. SimpleAPITest7

scala $OPTIONS interpolation-bug.scala
scala $OPTIONS scope-bug.scala

scala $OPTIONS TheoryTest.scala
scala $OPTIONS TheoryTest2.scala
scala $OPTIONS TheoryTest3.scala
