#!/bin/sh

unset CLASSPATH

rm -f *.class

OPTIONS="-language:implicitConversions,postfixOps,reflectiveCalls -cp `pwd`/../../bin"
RUNOPTIONS="-cp `pwd`/../../bin:."

export JAVA_OPTS="-Xss20000k -Xmx1500m"

TESTS="SimpleAPITest SimpleAPITest2 SimpleAPITest3 SimpleAPITest4 \
       SimpleAPITest5 SimpleAPITest6 SimpleAPITest7 SimpleAPITest8 \
       SimpleAPITest9 SimpleAPITest10 SimpleAPITest11"

for testname in $TESTS; do
  echo
  echo $testname
  scalac $OPTIONS $testname.scala
  scala $RUNOPTIONS $testname
done

scala $OPTIONS interpolation-bug.scala
scala $OPTIONS scope-bug.scala
scala $OPTIONS incrementality-bug.scala
scala $OPTIONS getConstraint-bug.scala

scala $OPTIONS TheoryTest.scala
scala $OPTIONS TheoryTest2.scala
scala $OPTIONS TheoryTest3.scala

scala $OPTIONS TypeTests.scala

scala $OPTIONS nonlinear.scala
scala $OPTIONS nonlinearInterpolation.scala
scala $OPTIONS division.scala

OPTIONS="-language:implicitConversions,postfixOps,reflectiveCalls -cp `pwd`/../../bin:`pwd`/../../extlibs/java-cup-11a.jar:`pwd`/../../smt-parser/smt-parser.jar"

scala $OPTIONS readSMTLIB.scala
scala $OPTIONS deadlock.scala
scala $OPTIONS exception.scala
scala $OPTIONS incremental.scala
scala $OPTIONS divmodprint.scala
scala $OPTIONS ADTTest.scala
scala $OPTIONS ADTTest2.scala
scala $OPTIONS ADTTest3.scala
scala $OPTIONS ADTTest4.scala
scala $OPTIONS pred-simplify.scala
scala $OPTIONS empty-stack-bug.scala

