#!/bin/sh

# tests only runnable with unit resolution

PRI=../../princess

TESTS="arrays0.pri arrays1.pri arrays2.pri \
       arrays0b.pri arrays1b.pri arrays2b.pri \
       SET027p3.pri SET063p3-clauses.pri \
       PUZ031p1-clauses.pri \
       functions2b.pri functions4.pri functions5.pri functions6.pri \
       sepLogic0.pri multiplication.pri multiplication2.pri \
       group1.pri betaTaskBug.pri factNormalisationBug.pri \
       instantiationBug.pri transitivityCounterExample.pri \
       arrayProperties.pri \
       eps1.pri eps2.pri eps3.pri eps4.pri \
       matchableCheckBug.pri negMatching.pri blockedOmegaBug.pri \
       mulTermination.pri adt2.pri adt3.pri adt4.pri \
       adt-cexes.pri adt-totality.pri adt-expand-nonterm.pri \
       pairs.pri pairs2.pri adt-nats.pri adt-size.pri"

$PRI "$@" $TESTS

$PRI "$@" -mulProcedure=bitShift mulTermination.pri
