#!/bin/sh

# test the TPTP parser

PRI=../../princess

TESTS="ARI120=1.p ARI496=1.p ARI595=1.p ARI616=1.p ARI620=1.p \
       ARI526=1.p ARI522=1.p \
       GEG021=1.p PUZ133=2.p SYN050-1.p \
       SYO561_1.p SYO563+1.p SYO563+2.p let-tests.p \
       quotes.p multiple-conjectures.p SYN340+1.p SYN340+1-mod.p"

$PRI "$@" $TESTS 2>&1 | grep -v '^Prover'

$PRI "$@" -timeout=60 PUZ001+1.p 2>&1 | grep -v '^Prover'

$PRI "$@" SWV032+1.p -assert +splitConjectures 2>&1 | grep -v '^Prover'
$PRI "$@" -assert ARI495\=1.p 2>&1 | grep -v '^Prover'

# will exit with an exception
$PRI "$@" SYN000_2.p

