#!/bin/sh

PRI=../../princess

# the returned constraints and witnesses are filtered out, because
# this data is too unstable and would cause the test cases to fail
# most of the time
find -name "*.pri" | sort | xargs $PRI "$@" 2>&1 | grep -v "^[(x!41\\]" | grep -v "^true"
