#!/bin/sh

PRI=../../princess

TESTS="bad-predicate-performance.pri \
       davisPutnam.pri \
       SET008+3.p \
       equiv.pri \
       equiv2.pri \
       simple-functions2.pri \
       functions10.pri \
       simple-functions.pri \
       infinite-domain-unsoundness2.p \
       infinite-domain-unsoundness3.pri \
       simple-predicate.pri \
       tarskiGeometry.pri"

$PRI "$@" $TESTS

$PRI "$@" -timeout=30000 +triggersInConjecture -genTotalityAxioms -tightFunctionScopes -clausifier=none +boolFunsAsPreds -triggerStrategy=allMaximal +ignoreQuantifiers -generateTriggers=all GEO212+3-complete.p

$PRI "$@"  -timeout=30000 SEU219+2.p -triggersInConjecture -genTotalityAxioms +tightFunctionScopes -clausifier=simple +reverseFunctionalityPropagation +boolFunsAsPreds -triggerStrategy=maximal -resolutionMethod=nonUnifying
