#!/bin/sh

find -name "*.scala" | \
(
    while read name; do
        echo $name
        mkdir -p ../src_assertionless/`dirname $name`
        gawk -f elimAssertions.awk <$name >../src_assertionless/$name
    done
)
