

all:
	$(SCALAC) $(SCALAC_OPTIONS) \
		ap/basetypes/*.scala \
		ap/util/*.scala \
		ap/terfor/*.scala \
		ap/terfor/conjunctions/*.scala \
		ap/terfor/equations/*.scala \
		ap/terfor/inequalities/*.scala \
		ap/terfor/arithconj/*.scala \
		ap/terfor/linearcombination/*.scala \
		ap/terfor/substitutions/*.scala \
		ap/terfor/preds/*.scala \
		ap/proof/*.scala \
		ap/proof/tree/*.scala \
		ap/proof/goal/*.scala \
		ap/proof/certificates/*.scala \
		ap/proof/theoryPlugins/*.scala \
		ap/parser/*.scala \
		ap/parameters/*.scala \
		ap/interpolants/*.scala \
		ap/theories/*.scala \
		ap/theories/nia/*.scala \
		ap/connection/*.scala \
		ap/*.scala

doc:
	$(SCALADOC) $(SCALAC_OPTIONS) $(SCALADOC_OPTIONS) \
		ap/basetypes/*.scala \
		ap/util/*.scala \
		ap/terfor/*.scala \
		ap/terfor/conjunctions/*.scala \
		ap/terfor/equations/*.scala \
		ap/terfor/inequalities/*.scala \
		ap/terfor/arithconj/*.scala \
		ap/terfor/linearcombination/*.scala \
		ap/terfor/substitutions/*.scala \
		ap/terfor/preds/*.scala \
		ap/proof/*.scala \
		ap/proof/tree/*.scala \
		ap/proof/goal/*.scala \
		ap/proof/certificates/*.scala \
		ap/proof/theoryPlugins/*.scala \
		ap/parser/*.scala \
		ap/parameters/*.scala \
		ap/interpolants/*.scala \
		ap/theories/*.scala \
		ap/theories/nia/*.scala \
		ap/connection/*.scala \
		ap/*.scala
