

all:
	$(SCALAC) $(SCALAC_OPTIONS) \
		main/scala/ap/basetypes/*.scala \
		main/scala/ap/util/*.scala \
		main/scala/ap/terfor/*.scala \
		main/scala/ap/terfor/conjunctions/*.scala \
		main/scala/ap/terfor/equations/*.scala \
		main/scala/ap/terfor/inequalities/*.scala \
		main/scala/ap/terfor/arithconj/*.scala \
		main/scala/ap/terfor/linearcombination/*.scala \
		main/scala/ap/terfor/substitutions/*.scala \
		main/scala/ap/terfor/preds/*.scala \
		main/scala/ap/proof/*.scala \
		main/scala/ap/proof/tree/*.scala \
		main/scala/ap/proof/goal/*.scala \
		main/scala/ap/proof/certificates/*.scala \
		main/scala/ap/proof/theoryPlugins/*.scala \
		main/scala/ap/parser/*.scala \
		main/scala/ap/parameters/*.scala \
		main/scala/ap/interpolants/*.scala \
		main/scala/ap/theories/*.scala \
		main/scala/ap/theories/nia/*.scala \
		main/scala/ap/theories/strings/*.scala \
		main/scala/ap/theories/sequences/*.scala \
		main/scala/ap/theories/bitvectors/*.scala \
		main/scala/ap/theories/rationals/*.scala \
		main/scala/ap/theories/arrays/*.scala \
		main/scala/ap/theories/heaps/*.scala \
		main/scala/ap/types/*.scala \
		main/scala/ap/algebra/*.scala \
		main/scala/ap/api/*.scala \
		main/scala/ap/*.scala

doc:
	$(SCALADOC) $(SCALAC_OPTIONS) $(SCALADOC_OPTIONS) \
		main/scala/ap/basetypes/*.scala \
		main/scala/ap/util/*.scala \
		main/scala/ap/terfor/*.scala \
		main/scala/ap/terfor/conjunctions/*.scala \
		main/scala/ap/terfor/equations/*.scala \
		main/scala/ap/terfor/inequalities/*.scala \
		main/scala/ap/terfor/arithconj/*.scala \
		main/scala/ap/terfor/linearcombination/*.scala \
		main/scala/ap/terfor/substitutions/*.scala \
		main/scala/ap/terfor/preds/*.scala \
		main/scala/ap/proof/*.scala \
		main/scala/ap/proof/tree/*.scala \
		main/scala/ap/proof/goal/*.scala \
		main/scala/ap/proof/certificates/*.scala \
		main/scala/ap/proof/theoryPlugins/*.scala \
		main/scala/ap/parser/*.scala \
		main/scala/ap/parameters/*.scala \
		main/scala/ap/interpolants/*.scala \
		main/scala/ap/theories/*.scala \
		main/scala/ap/theories/nia/*.scala \
		main/scala/ap/theories/strings/*.scala \
		main/scala/ap/theories/sequences/*.scala \
		main/scala/ap/theories/bitvectors/*.scala \
		main/scala/ap/theories/rationals/*.scala \
		main/scala/ap/theories/arrays/*.scala \
		main/scala/ap/types/*.scala \
		main/scala/ap/algebra/*.scala \
		main/scala/ap/api/*.scala \
		main/scala/ap/*.scala
