#!/bin/sh

# tests in SMT-LIB format

PRI=../../princess

TESTS="simple-heap.smt2 \
       simple-heap-sat.smt2 \
       read-interpolation-1.smt2 \
       read-interpolation-1b.smt2 \
       read-interpolation-2.smt2 \
       read-interpolation-3.smt2 \
       read-interpolation-4.smt2 \
       read-interpolation-5.smt2 \
       alloc-interpolation-1.smt2 \
       alloc-interpolation-1b.smt2 \
       alloc-interpolation-2.smt2 \
       alloc-interpolation-3.smt2 \
       alloc-interpolation-3b.smt2 \
       alloc-interpolation-3c.smt2 \
       simple-heap-allocAddr.smt2 \
       simple-heap-batch.smt2 \
       simple-heap-batch-sat.smt2 \
       heap-batch-write-read-1-unsat.smt2 \
       heap-batch-write-read-2-unsat.smt2 \
       adt-addrrange-sat.smt2 \
       adt-addrrange-unsat.smt2 \
       extensionality-bug.smt2 \
       heap-empty-alloc-range.smt2"

$PRI "$@" -heapSolver=native $TESTS
$PRI "$@" -heapSolver=array $TESTS

TESTS="bug-model-1.smt2 \
       incremental-heap.smt2 \
       swap-interpolation.smt2 \
       heap-batch-write-read-2-sat.smt2 \
       queries.smt2"

$PRI "$@" +incremental -heapSolver=native $TESTS
$PRI "$@" +incremental -heapSolver=array $TESTS


